### ISSUE TITLE
Package not working when updated to latest version

### ISSUE THREAD

**Issue by vivekgadgeon** [jasminmakasana/flutter_kinesis_video_webrtc#1]
I was working on package version 0.0.3. It was working fine until we tried installing the version 0.0.9. Now It is hanging on "ICE-CANDIDATE" portion. It is not getting connected to the master. I am testing this in iPhone 14, iOS 17.2.1. Can you check what is the issue?

**Comment by pankaj-kharche-programmersio** [comment]
Hi @vivekgadgeon, I am trying to live video streaming from SignalingClient AWS Kinesis, but facing above mention issue, are you able to solve it, please let me know. Thank you

**Comment by djaviya118389** [comment]
@vivekgadgeon or @pankaj-kharche-programmersio can you share your error and flutter sdk version i'll check in detail ASAP thank you.

and please use only flutter_kinesis_video_webrtc 0.0.9 (latest version) older version has small bugs and does not support latest flutter SDK 
check example also

**Comment by pankaj-kharche-programmersio** [comment]
Hello @jasminmakasana and @djaviya118389, Please see attached log, remote video not rendering, Thank you.

Launching lib/main.dart on GM1901 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
W/FlutterWebRTCPlugin(18363): audioFocusChangeListener [Earpiece(name=Earpiece)] Earpiece(name=Earpiece)
W/FlutterWebRTCPlugin(18363): audioFocusChangeListener [Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] Speakerphone(name=Speakerphone)
Debug service listening on ws://127.0.0.1:56174/qDZoyFcU3TU=/ws
Syncing files to device GM1901...
D/ViewRootImpl[MainActivity](18363):  debugCancelDraw some OnPreDrawListener onPreDraw return false,cancelDraw=true,count=50,android.view.ViewRootImpl@f3b3971
I/ample.kvswebrt(18363): Compiler allocated 4114KB to compile void android.view.ViewRootImpl.performTraversals()
I/org.webrtc.Logging(18363): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(18363): NativeLibrary: Loading library: jingle_peerconnection_so
I/org.webrtc.Logging(18363): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/org.webrtc.Logging(18363): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
I/org.webrtc.Logging(18363): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
I/org.webrtc.Logging(18363): JavaAudioDeviceModule: createAudioDeviceModule
I/org.webrtc.Logging(18363): JavaAudioDeviceModule: HW NS will be used.
I/org.webrtc.Logging(18363): JavaAudioDeviceModule: HW AEC will be used.
I/org.webrtc.Logging(18363): WebRtcAudioEffectsExternal: ctor@[name=main, id=2]
I/org.webrtc.Logging(18363): WebRtcAudioRecordExternal: ctor@[name=main, id=2]
I/org.webrtc.Logging(18363): WebRtcAudioTrackExternal: ctor@[name=main, id=2]
I/org.webrtc.Logging(18363): EglBase14Impl: Using OpenGL ES version 2
W/AudioCapabilities(18363): Unsupported mime audio/ffmpeg
W/VideoCapabilities(18363): Unsupported mime video/ffmpeg
W/VideoCapabilities(18363): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(18363): Unrecognized profile/level 0/3 for video/mpeg2
I/org.webrtc.Logging(18363): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging(18363): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging(18363): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging(18363): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging(18363): PeerConnectionFactory: onWorkerThreadReady
I/org.webrtc.Logging(18363): PeerConnectionFactory: onSignalingThreadReady
I/org.webrtc.Logging(18363): PeerConnectionFactory: onNetworkThreadReady
I/Quality (18363): Skipped: false 8 cost 133.6592 refreshRate 0 processName com.example.kvswebrtc
I/org.webrtc.Logging(18363): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(18363): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging(18363): EglBase14Impl: Using OpenGL ES version 2
D/SurfaceComposerClient(18363): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
D/ViewRootImpl[MainActivity](18363):  debugCancelDraw  cancelDraw=false,count = 238,android.view.ViewRootImpl@f3b3971
D/SurfaceComposerClient(18363): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4012 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/flutter (18363): -----channel ARN----->arn:aws:kinesisvideo:us-east-1:997532399291:channel/sample/1818398829959
I/flutter (18363): -----channel endPoint----->https://r-13e2a5fc.kinesisvideo.us-east-2.amazonaws.com
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4013 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4009 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/flutter (18363): SimpleWebSocket: Allow self-signed certificate => v-ef08a1db.kinesisvideo.us-east-1.amazonaws.com:443. 
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/flutter (18363): -------------------- socket opened --------------------
I/flutter (18363): -------------------- sending 'SDP_OFFER' --------------------
I/org.webrtc.Logging(18363): NetworkMonitor: Start monitoring with native observer -5476376623244136608 fieldTrialsString: 
D/FlutterWebRTCPlugin(18363): onIceGatheringChangeGATHERING
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: Network handle: 626175954957 becomes available: 145
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: handle: 626175954957 capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=86750Kbps LinkDnBandwidth>=43274Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, Security type: 2, Supplicant state: COMPLETED, HE Eight Max VHT Spatial Streams Supported AP: false, Eight Max VHT Spatial streams support: false, Wi-Fi standard: 4, RSSI: -47, Link speed: 144Mbps, Tx Link speed: 144Mbps, Max Supported Tx Link speed: 144Mbps, Rx Link speed: 144Mbps, Max Supported Rx Link speed: 144Mbps, Frequency: 2412MHz, Net ID: -1, Metered hint: false, score: 51, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1> SignalStrength: -47 UnderlyingNetworks: Null]
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: handle: 626175954957 link properties changed
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: Network handle: 621880987661 becomes available: 144
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: handle: 621880987661 capabilities changed: [ Transports: CELLULAR Capabilities: SUPL&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=528536Kbps LinkDnBandwidth>=132858Kbps Specifier: <TelephonyNetworkSpecifier [mSubId = 1]> UnderlyingNetworks: Null]
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/org.webrtc.Logging(18363): NetworkMonitorAutoDetect: handle: 621880987661 link properties changed
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
D/FlutterWebRTCPlugin(18363): onIceCandidate
I/flutter (18363): -------------------- sending 'ICE_CANDIDATE' --------------------
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4019 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4016 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4014 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4023 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4024 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4024 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4021 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
D/FlutterWebRTCPlugin(18363): onIceGatheringChangeCOMPLETE
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4013 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4014 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4014 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4009 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(18363): EglRenderer: Duration: 4013 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by djaviya118389** [comment]
@pankaj-kharche-programmersio this package is only for receivers. you can see you are not receiving any ice candidates. first, you have to start master with your AWS credentials on this web page [AWS test page]( https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/) and Then try connecting to the same channel you started the master with

any other issue feel free to ask 
thank you

**Comment by pankaj-kharche-programmersio** [comment]
@djaviya118389, the master is already started and then after I have taken above shared logs. I can see master video streaming in AWS test page but not in that app.

**Comment by djaviya118389** [comment]
@pankaj-kharche-programmersio please check the example app and implement all the functions given in the example

**Comment by pankaj-kharche-programmersio** [comment]
Already running given sample example after modifying details for `SignalingClient`. Thank you for your response @djaviya118389. Still the remote video not streaming.

**Comment by djaviya118389** [comment]
@pankaj-kharche-programmersio we working on that thanks for updating

**Comment by djaviya118389** [comment]
the package is working fine @pankaj-kharche-programmersio  Please check full-example and flutter_kinesis_video_webrtc 0.0.9

**Comment by dsoltis3** [comment]
@djaviya118389 I'm seeing the same issue with the example. I have a master running using the AWS test page and when I run the example the master never receives the SDP offer. I'm able to successfully connect a viewer to the master using the same credentials on a different pc from the AWS test page. Any help would be appreciated. My debug logs are the same as @pankaj-kharche-programmersio

**Comment by djaviya118389** [comment]
@dsoltis3 Sorry to hear that but use the latest version of the flutter_kinesis_video_webrtc  package (0.0.9)
it's working as expected are you have any other issues let me know we are connect on another platform like Google Meet
thanks

**Comment by dsoltis3** [comment]
That would be great. Could you email me at don@tarracor.com? Thanks!
