### ISSUE TITLE
Create call

### ISSUE THREAD

**Issue by Dashstack0003** [jasminmakasana/flutter_kinesis_video_webrtc#2]
In this repository, I could not find the create call code.

**Comment by djaviya118389** [comment]
we don't understand what are you looking for but all the steps to connect WEBRTC and make the call is in example application can you specify what are you looking for?
thank you
@Dashstack0003

**Comment by Dashstack0003** [comment]
To create a video call code in the repository, please help me.
@djaviya118389

**Comment by Dashstack0003** [comment]
Using AWS Kenisis, I would like to establish a video conference between two people.
Could you please assist me, @djaviya118389?
